services:
  chat-server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8080:8080
  chat-client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    environment:
      NODE_ENV: development
      # for production
      # NODE_ENV: production
    ports:
      - 3000:3000

volumes:
  database:
